add channel arguments to snaps in the action
charmed-kubernetes/actions-operator pull request #28
Opened 2021-11-12 21:01 UTC by ca-scribner

2021-11-12 21:07 UTC, ca-scribner commented
I see the other channel args were left as `default_value=null` and then use if statements.  I ended up using `default=latest/stable` so all calls could be `snap install ... --channel=${this_channel}` to avoid a few extra lines, but I can change it to match the current format if that's preferred.

2021-11-12 21:26 UTC, knkski commented on src/bootstrap/index.ts
> +        await exec.exec("sudo snap install juju-bundle --channel=${juju_channel}");
This is setting it for `juju-bundle` instead of for `juju`

2021-11-12 21:35 UTC, knkski approved these changes

2021-11-15 18:59 UTC, johnsca requested changes
In addition to the comment below, you also need to run `npm run build`. There's a pre-commit hook in the repo under `.github/hooks/pre-commit` that I recommend you symlink into your `.git/hooks/` directory to catch that.

Also, the PR probably doesn't need to be a draft anymore.

2021-11-15 18:59 UTC, johnsca commented on src/bootstrap/index.ts
> +        await exec.exec("sudo snap install juju --classic --channel=${juju_channel}");
You have to use backtick quotes for interpolation to work (this also applies to the other lines).

```suggestion
        await exec.exec(`sudo snap install juju --classic --channel=${juju_channel}`);
```

2021-11-15 19:04 UTC, ca-scribner commented on src/bootstrap/index.ts
> +        await exec.exec("sudo snap install charm --classic --channel=${charm_channel}");
```suggestion
        await exec.exec(`sudo snap install charm --classic --channel=${charm_channel}`);
```

2021-11-15 19:04 UTC, ca-scribner commented on src/bootstrap/index.ts
> +        await exec.exec("sudo snap install juju-bundle --channel=${juju_bundle_channel}");
```suggestion
        await exec.exec(`sudo snap install charm --classic --channel=${charm_channel}`);
        await exec.exec(`sudo snap install charmcraft --channel=${charmcraft_channel}`);
        await exec.exec(`sudo snap install juju-bundle --channel=${juju_bundle_channel}`);
```

2021-11-15 19:57 UTC, johnsca approved these changes

2021-11-15 19:57 UTC, merged