Adds optional addons for microk8s
charmed-kubernetes/actions-operator pull request #45
Opened 2022-11-24 14:18 UTC by kian99

Copied from #33:

> In order to be able to use the nginx-ingress-integrator charm and other related charms, we need to enable ingress in microk8s.
> 
> This adds the microk8s-addons option, which will contain the addons to be enabled in microk8s. If not given, the default addons will be added instead (storage, dns, rbac).

This PR can be merged in favor of the original, it simply adds the original changes on top of the latest commit in main. An example use can be found [here](https://github.com/canonical/xyz/actions/runs/3540009136/jobs/5942565602) with corresponding [workflow file](https://github.com/canonical/xyz/actions/runs/3540009136/workflow).

Fixes #32

2022-11-28 16:53 UTC, ca-scribner commented on src/bootstrap/index.ts
> +    addons = addons || "storage dns rbac"
I think this blocks someone from using no addons (eg: `""`).  If `addons=""`, then it will get replaced with the defaults.  

I'd be ok if we left defining defaults to the `action.yaml` file (which has the original `storage dns rbac`), and then this function just applies whatever `addons` it receives without additional parsing.  Thoughts?

We should probably add a test for this too.  Maybe a test in the e2e.yaml with cases:
* `default=[unset]`: this should result in dns, storage, and rbac being enabled
* `default=""`: this should result in dns, storage, and rbac **not** being enabled

2022-11-28 16:53 UTC, ca-scribner requested changes
One change and maybe an associated test, otherwise lgtm

2022-11-28 16:54 UTC, ca-scribner commented
The microstack and vSphere tests are failing, but this is to be expected as the PR is from a fork and those tests require credentials from secrets.

2022-11-29 07:24 UTC, kian99 commented on src/bootstrap/index.ts
> +    addons = addons || "storage dns rbac"
This makes good sense. I'll add a check, if addons is not empty, we'll enable whatever is passed in.

2022-11-29 15:25 UTC, ca-scribner commented on src/bootstrap/index.ts
> +    addons = addons || "storage dns rbac"
These changes and the Readme look great.  I'm starting a new conversation on the matrix value over at that part of the code to discuss that as I'm also not sure how it'll work.

2022-11-29 15:49 UTC, kian99 commented on .github/workflows/e2e.yaml
> +          - []
Ah fair, two separate tests makes life easier. For the assertion I'll add a step that will just run `microk8s status` and check the output includes the expected items. Do you think I should still also run the charm builds as well on those tests?

2022-11-29 18:14 UTC, ca-scribner commented
I don’t think the charm builds are needed. Simply asking microk8s sounds
perfect

On Tue, Nov 29, 2022 at 10:50 Kian Parvin ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .github/workflows/e2e.yaml
> <https://github.com/charmed-kubernetes/actions-operator/pull/45#discussion_r1034934261>
> :
>
> > +    strategy:
> +      matrix:
> +        addons:
> +          - ""
> +          - []
>
> Ah fair, two separate tests makes life easier. For the assertion I'll add
> a step that will just run microk8s status and check the output includes
> the expected items. Do you think I should still also run the charm builds
> as well on those tests?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/charmed-kubernetes/actions-operator/pull/45#discussion_r1034934261>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALPFPI5O4ARR5WWZDZQNYI3WKYQ25ANCNFSM6AAAAAASKOMJTI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-11-30 07:45 UTC, kian99 commented
I've added a test that will parse the output of microk8s status and ensure only the desired addons are enabled. But just a note that microk8s enables 3 addons by default (ha-cluster, helm, helm3) so I've also catered for that.

2022-12-14 08:53 UTC, kian99 commented
Done by #46, closing.

2022-12-14 08:53 UTC, closed without merging