Validate return codes when initializing microk8s
charmed-kubernetes/actions-operator pull request #59
Opened 2023-08-24 18:08 UTC by DanielArndt

Without this change, if the `can-i` commands failed, the build would ignore it and continue.

Furthermore, the `can-i --as=me` command is only relevant when RBAC is enabled, so this change also checks for that before waiting on that command.

2023-08-25 13:38 UTC, addyess requested changes
You'll need to build this and check in the resulting built js files

I'm kinda confused on the parse addons.  Honestly this action should probably list those inputs as a list of strings rather than  space separated strings... too late now

```bash
sudo snap install node --classic
export NODE_OPTIONS=--openssl-legacy-provider
npm run build
```


```

2023-08-25 13:38 UTC, addyess commented on src/bootstrap/index.ts
> +
Help me on this... my understanding is addons is a space separated string that lists the microk8s addons needed

```yaml
  microk8s-addons:
    description: "microk8s addons to enable"
    required: false
    default: "storage dns rbac"
```

i get the `addons.split(" ")` but am confused why the split on colon does?

2023-08-25 13:38 UTC, addyess commented on src/bootstrap/index.ts
> +
@neoaggelos i suppose this makes sense microk8s-wise

2023-08-28 11:59 UTC, DanielArndt commented on src/bootstrap/index.ts
> +
The colon is because, optionally, you can provide a version. For example, I saw this in one usage:

```
          microk8s-addons: "hostpath-storage metallb:10.1.1.1-10.1.1.254"
```

2023-08-28 12:01 UTC, DanielArndt commented on src/bootstrap/index.ts
> +
Admittedly, I got this understanding from a quick local test, and skimming (and inferring) from https://www.yld.io/blog/testing-kubernetes-rbac/ that this only makes sense when RBAC is enabled.

>     kubectl auth can-i create pods --as=me
> We should see that we now get a “no” returned with an exit code of 1 being returned.

Definitely not my area of expertise, though.

2023-08-28 12:03 UTC, DanielArndt commented
> Honestly this action should probably list those inputs as a list of strings rather than space separated strings... too late now

Yes, I agree. I considered making this change, but didn't want to go down the road of changing the contract for this fix. I agree that's the best long-term approach, but would probably be a breaking change unless we wanted to add some backward compatibility.

2023-08-28 18:23 UTC, DanielArndt commented on src/bootstrap/index.ts
> +
Whoops, guess those are IPs, not a version... so just passing parameters to the addon I guess.

2023-09-14 19:36 UTC, DanielArndt commented
@addyess 

> You'll need to build this and check in the resulting built js files

Sorry for the delay here. I had an error about missing `ncc` and didn't have time to figure out what was going on until now. I needed to do an `npm install --include=dev` as well.

2024-03-18 15:46 UTC, DanielArndt commented
Closing as this has gone stale

2024-03-18 15:46 UTC, closed without merging