Add input for setting docker registry for microk8s
charmed-kubernetes/actions-operator pull request #63
Opened 2023-12-12 04:47 UTC by yhaliaw

WIP

2023-12-12 04:51 UTC, jdkandersson approved these changes

2023-12-12 13:21 UTC, jdkandersson approved these changes

2023-12-12 13:44 UTC, addyess commented
i'd REALLY like @neoaggelos to take a look at this but he may not have a moment to do so.

2023-12-12 13:46 UTC, neoaggelos requested changes
Instead of exec, please use File IO. Also, microk8s stop/start is not required, prefer `snap restart microk8s.daemon-containerd`, or nothing at all (the config applies immediately

2023-12-12 19:42 UTC, addyess commented on src/bootstrap/index.ts
> +    const microk8s_docker_registry = core.getInput("microk8s-docker-registry") || process.env["MICROK8S_DOCKER_REGISTRY"]
@yhaliaw -- here's how to use  the action input or environment variable

2023-12-13 03:30 UTC, yhaliaw commented on src/bootstrap/index.ts
> +    const microk8s_docker_registry = core.getInput("microk8s-docker-registry") || process.env["MICROK8S_DOCKER_REGISTRY"]
Can `DOCKERHUB_MIRROR` be used as the env var instead?
I have updated the code.

2023-12-13 03:35 UTC, addyess commented on src/bootstrap/index.ts
> +    const microk8s_docker_registry = core.getInput("microk8s-docker-registry") || process.env["DOCKERHUB_MIRROR"]
so? why is one `DOCKERHUB_MIRROR` and the other `microk8s-docker-registry`

feels to me these ought to be consistent.

Is the intent here to use a replacement oci-registry?

I kinda like either `container-registry-url` or `oci-registry-url` and just drop the "microk8s" bit.  
then have the env var `CONTAINER_REGISTRY_URL` or `OCI_REGISTRY_URL`

2023-12-14 02:22 UTC, yhaliaw commented on src/bootstrap/index.ts
> +    const microk8s_docker_registry = core.getInput("microk8s-docker-registry") || process.env["DOCKERHUB_MIRROR"]
Updated the `microk8s-docker-registry` to `container-registry-url` in the code

2023-12-14 02:23 UTC, jdkandersson approved these changes

2023-12-14 16:56 UTC, merged