swap pip with pipx
charmed-kubernetes/actions-operator pull request #90
Opened 2024-12-05 04:13 UTC by yanksyoon

2024-12-05 14:44 UTC, addyess commented
@yanksyoon is this the same issue https://github.com/charmed-kubernetes/actions-operator/issues/82

Overall, i don't hate looking for `pipx` on the worker and using it for installing tox, I guess i can see how using pipx rather than pip to globally install applications might be okay since it handles sandboxing the dependencies for that application.  

Its gonna take some time to figure out why the tests are failing though...

2024-12-05 14:45 UTC, addyess commented on src/bootstrap/index.ts
> +    await exec.exec("sudo pipx ensurepath");
can you fill me in on why you've got this?

2024-12-05 15:47 UTC, addyess commented
I looked at the failed tests, and resolved them.  Rebase to pick those up

2024-12-05 16:47 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    await exec.exec("sudo pipx ensurepath");
This is to add the `pipx` managed installations be available to the users. It adds the pipx directories to $PATH.
So this allows sudo user and ubuntu users to use things installed via pipx :)

2024-12-05 16:54 UTC, yanksyoon commented
@addyess I've merged main :D Not quite sure if something might be required to run the tests though!

2024-12-05 21:47 UTC, addyess commented on src/bootstrap/index.ts
> +    await exec.exec("sudo pipx ensurepath");
Great thanks!

2024-12-05 21:54 UTC, addyess requested changes
Do you think you can implement the suggestion?

2024-12-05 21:54 UTC, addyess commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
ok, the only thing i'm a little bothered by here is that i've suggested users on noble and beyond to use the `setup_python` action in front of actions-operator so that pip is on the machine and in the path -- but it's not the system path.  With pipx, we're going about this the right way but those folks with `setup_python` now won't really be using it.  It's an extra step.  

`hasPip` just tells us that pip is in the path somewhere, as a boolean.  it doesn't tell us where it is.   System level `pip` can't install packages like tox or black, but `setup_python` installed `pip` can.  So we've got a dilemma here. 

We'd like to avoid using system pip -- agree, but i'd like to continue using `setup_python` pip if it's there.  

Sounds like I want this:
if has non-python system path pip -- install tox with it
otherwise -- USE pipx and install tox${version} with it

2024-12-06 03:38 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
I see - I've read [PEP668](https://peps.python.org/pep-0668/#marking-an-interpreter-as-using-an-external-package-manager) to see how to determine an external package manager vs a system package manager.
In summary, the following conditions should be true to be an external packager manager:

1. sys.prefix != sys.base_prefix
2. EXTERNALLY-MANAGED file in the directory identified by sysconfig.get_path("stdlib", sysconfig.get_default_scheme())

This methods will require launching a python script.

However, we could assume a few things and just check `which python3`.
From this [test run](https://github.com/canonical/cbartz-runner-testing/actions/runs/12192447270/job/34013083515), i can see that `which python3/pip3/python/pip` results in a path that is not `/usr/bin/python3` (`/home/ubuntu/actions-runner/_work/_tool/Python/3.13.1/x64/bin/python3`). 
I think this check might be enough for me to guarantee that it is an externally managed Python/Pip, rather than having to go through what is suggested by PEP668.

What do you think?

2024-12-06 04:10 UTC, addyess commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
yeah absolutely.  If `which pip` ends up in `/usr/bin/python3` -- it's they system package.  I'm okay with this resolution.  Are you comfortable changing this method to find which pip is being called?

likely something like:

```typescript
const pip_path = await checkOutput("which", ["pip"], ignoreFail);
const sys_pip = pip_path == "/usr/bin/pip";
```

2024-12-06 04:30 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
Updated :)

2024-12-06 04:30 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
let me test both cases

2024-12-06 04:32 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
https://github.com/canonical/cbartz-runner-testing/actions/runs/12192986653

2024-12-06 05:17 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
Successful runs:
only system pip (use pipx): https://github.com/canonical/cbartz-runner-testing/actions/runs/12193209000/job/34015081724#step:3:47
python actions (use external pip):  https://github.com/canonical/cbartz-runner-testing/actions/runs/12193209000/job/34015081846#step:5:53

This PR can now be safely merged :)

2024-12-06 05:18 UTC, yanksyoon commented on src/bootstrap/index.ts
> +    const hasPipx = await exec.exec("which pipx", [], ignoreFail);
@addyess

2024-12-06 05:21 UTC, addyess approved these changes
LGTM.  Nice!

2024-12-06 13:43 UTC, merged